website:
  title: "Emmanuel Naatei Nartey"
  description: "Emmanuel N. Nartey is a biostatistician"  
  navbar:
    left:
      - text: "Research"
        href: research/index.qmd
      - text: "Bookmarks"
        href: bookmarks/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "CV"
        href: cv/index.qmd
       
        
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/emmarteyn/
      - icon: twitter
        href: https://x.com/emmartey
      - icon: envelope
        aria-label: email
        href: "mailto:mail.enarteynaatei@gmail.com"  
        

  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Emmanuel Naatei Nartey CC BY-SA 4.0</span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>


project:
  type: website
  output-dir: docs




  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

